export const portfolioSeed = [
  {
    slug: "real-estate-ai-assistant",
    title: "Real Estate AI Assistant",
    metric: "-35% review time",
    summary:
      "LLM + RAG combined with document intelligence to verify and classify real-estate records faster.",
    tags: ["LLM", "RAG", "Real Estate"],
    category: "AI Products",
    image: "/portfolio/banner/real_estate_AI_assistant.webp",
    route: "/portfolio/real-estate-ai-assistant",
    featured: true,
    sortOrder: 1,
  },
  {
    slug: "high-traffic-web-platform",
    title: "High-traffic Web Platform",
    metric: "<300ms latency",
    summary:
      "Scalable web platform handling 1,000+ concurrent users with real-time synchronization.",
    tags: ["WebSockets", "Cloud", "Scale"],
    category: "Software & Firmware Development",
    image: "/portfolio/banner/high_traffic_web_platform.webp",
    route: "/portfolio/high-traffic-web-platform",
    sortOrder: 2,
  },
  {
    slug: "fintech-verification-ai",
    title: "Fintech Verification AI",
    metric: "95%+ accuracy",
    summary:
      "Document AI pipeline for fintech verification with OCR, classification, and quality checks.",
    tags: ["Computer Vision", "OCR", "Fintech"],
    category: "AI Products",
    image: "/portfolio/banner/fintech_verification_AI.webp",
    route: "/portfolio/fintech-verification-ai",
    sortOrder: 3,
  },
  {
    slug: "government-document-ai-2",
    title: "Government Document AI",
    metric: "60% faster processing",
    summary:
      "Secure LLM-powered retrieval and summarization workflow for government document archives.",
    tags: ["NLP", "Document AI", "Gov Tech"],
    category: "AI Products",
    image: "/portfolio/banner/government_document_AI.webp",
    route: "/portfolio/government-document-ai-2",
    sortOrder: 4,
  },
  {
    slug: "marketing-content-assistant-2",
    title: "Marketing Content Assistant",
    metric: "3x content output",
    summary:
      "AI content workspace helping teams create campaign assets faster with consistent quality.",
    tags: ["Content Gen", "Automation", "Marketing"],
    category: "AI Products",
    image: "/portfolio/banner/marketing_content_assistant.webp",
    route: "/portfolio/marketing-content-assistant-2",
    sortOrder: 5,
  },
];

export const solutionsSeed = [
  {
    slug: "ai-products",
    title: "AI Products",
    desc: "A suite of AI products that automates analysis, Q&A, and real-time decision making through advanced neural networks.",
    image: "/AI_Product.webp",
    features: [
      "Predictive Analytics",
      "Natural Language Processing",
      "Real-time Q&A",
    ],
    route: "/solutions/ai-products-2",
    category: "Artificial Intelligence",
    metric: "50+ deployments",
    accent: "from-cyan-500 to-sky-500",
    icon: "Sparkles",
    sortOrder: 1,
  },
  {
    slug: "industrial-ai-automation",
    title: "Industrial AI & Automation",
    desc: "End-to-end industrial AI solutions for computer vision inspection, failure prediction, and seamless factory integration.",
    image: "/IndustrialAI.webp",
    features: ["Defect Detection", "Predictive Maintenance", "IoT Integration"],
    route: "/solutions/coming-soon",
    category: "Industrial Automation",
    metric: "<120ms inference",
    accent: "from-blue-500 to-indigo-500",
    icon: "Cpu",
    sortOrder: 2,
  },
  {
    slug: "software-firmware-development",
    title: "Software & Firmware Development",
    desc: "Expert software engineering and embedded system development tailored for enterprise-grade products and platforms.",
    image: "/softwareAndFirmware.webp",
    features: ["Custom Web/App", "Embedded C/C++", "Cloud Architecture"],
    route: "/solutions/software-firmware-development-2",
    category: "Software Development",
    metric: "99.9% reliability",
    accent: "from-teal-500 to-cyan-500",
    icon: "Layers",
    sortOrder: 3,
  },
];
